filter:
    excluded_paths: [vendor/*, test/*, examples/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true
build:
    dependencies:
        after:
            - 'sudo rabbitmq-plugins enable rabbitmq_management'
            - 'sudo service rabbitmq-server restart'
            - 'sudo rabbitmqctl status'
    environment:
        rabbitmq: true
        php:
            version: 7.0.8


