filter:
    excluded_paths: [vendor/*, test/*, examples/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true
build:
    environment:
        php:
            version: 7.0
