filter:
    excluded_paths: [vendor/*, test/*, examples/*]
checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover.xml'
                coverage:
                    file: 'src/coverage.clover.xml'
                    format: 'clover'
    dependencies:
        after:
            - 'wget --progress=bar:force http://www.rabbitmq.com/releases/rabbitmq-server/v3.5.7/rabbitmq-server_3.5.7-1_all.deb'
            - 'sudo dpkg -i rabbitmq-server_3.5.7-1_all.deb'
            - 'sudo rabbitmq-plugins enable rabbitmq_management'
            - 'sudo service rabbitmq-server restart'
            - 'sudo rabbitmqctl status'
    environment:
        rabbitmq: true
        php:
            version: 7.0.8


build:
