filter:
    excluded_paths: [vendor/*, tests/*, examples/*]
checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 7.0
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.html'
                coverage:
                    file: 'coverage.html'
                    format: 'clover'
